spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      ssl:
        enabled: true
  cache:
    ttl-minutes: ${REDIS_TTL_MINUTES}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}_prod
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT}

logging:
  level:
    root: WARN
    com.leedTech: INFO

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false